stages:
  - build
  - docker

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# -------- Gradle Build --------
gradle-build:
  stage: build
  image: gradle:8.10.2-jdk17
  script:
    - cd BankingBackend
    - gradle clean build -x test
  artifacts:
    paths:
      - BankingBackend/build/libs/*.jar

# -------- Docker Build & Push --------
docker-build:
  stage: docker
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
